In [1]:
import numpy as np
print(np.__version__)

1.26.4


In [2]:
arr1 = np.array([11,22,33,44,55])
print("The array is : ",arr1)

The array is :  [11 22 33 44 55]


In [4]:
print("type of array : ", type(arr1))

type of array :  <class 'numpy.ndarray'>


In [9]:
arr2 = np.array([77,88,99,100])
print("The array is : ",arr2)
print(type(arr2))

The array is :  [ 77  88  99 100]
<class 'numpy.ndarray'>


In [12]:
arr3 = np.array([[1,2,3],[4,5,6]])
print(arr3)
print("The number of dimensions: ",arr3.ndim)
print("The shape of array: ",arr3.shape)

[[1 2 3]
 [4 5 6]]
The number of dimensions:  2
The shape of array:  (2, 3)


In [15]:
arr4 = np.array([[[1,2,3],[4,5,6]], [[11,22,33],[44,55,66]]])
print(arr4)
print("The number of dimensions: ",arr4.ndim)
print("The shape of array: ",arr4.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 22 33]
  [44 55 66]]]
The number of dimensions:  3
The shape of array:  (2, 2, 3)


In [16]:
#Create a 0 dimension array or scalar 
import numpy as np
arr = np.array(10)
print(arr)

10


In [17]:
# Create 1-d array using list objects
arr = np.array([10,11,12,13,14,15]) # list of elements
print(arr) # array syntax has list brackets but no commas 

[10 11 12 13 14 15]


In [18]:
print(arr[0],arr[2],arr[5]) # in square brackets index value is passed 

10 12 15


In [5]:
# create a 2d array 
import numpy as np
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr1)
print("The size of array : ",arr1.size)
print(type(arr1))
print("The shape of array: ",arr1.shape)
# pick up an element write the row no. and column no.
print("arr1[0,0] : ",)
print("arr1[2,3] : ",)

# to check the datatype of each array itnem dtype is used 
print("Datatype of each element of arr1= : ",arr1.dtype)
                

[[1 2 3]
 [4 5 6]
 [7 8 9]]
The size of array :  9
<class 'numpy.ndarray'>
The shape of array:  (3, 3)
arr1[0,0] : 
arr1[2,3] : 
Datatype of each element of arr1= :  int32


In [25]:
import numpy as np
arr = np.array({'w','t','h','k'})
print(arr) # no indexing in sets 
print(type(arr))
print(arr.ndim)
print(arr.size) 

{'w', 't', 'k', 'h'}
<class 'numpy.ndarray'>
0
1


In [ ]:
# reshape() function is used to reshape the array
# it takes two parameters - rows and columns 
# the reshaped array must maintain size compatibility 


In [7]:
arr1 = np.array([(10,1),(20,2),(30,3),(40,4)],complex)
print(arr1)
print(arr1.shape)
print(arr1.ndim)

[[10.+0.j  1.+0.j]
 [20.+0.j  2.+0.j]
 [30.+0.j  3.+0.j]
 [40.+0.j  4.+0.j]]
(4, 2)
2


In [12]:
# we can assign any number of dimensions to an array by using ndmin 
arr4 = np.array([1,2,3,4,5,6,7,8],ndmin = 4,dtype = complex )
print("arr4: ",arr4)
print("The number of dimensions are : ",arr4.ndim)  # ndim tells no. of dimensions

arr4:  [[[[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j 6.+0.j 7.+0.j 8.+0.j]]]]
The number of dimensions are :  4


In [14]:
#iteration in 1d array
arr1 = ([1,2,3,4,5])
for i in arr1:
    print( "iteration: ",i)

iteration:  1
iteration:  2
iteration:  3
iteration:  4
iteration:  5


In [24]:
arr2 = ([[1,2,3],[5,6,7],[8,9,10]])
# for loop to print each row
# declaring int as integer in advance
count: int = 0
for row in arr2:
 count = count +1 
print( "row:" ,count," : ",row)

# to print individual elements of row
for row in arr2:
 for i in row: 
  print("all elements of row are: ",i)

row: 3  :  [8, 9, 10]
all elements of row are:  1
all elements of row are:  2
all elements of row are:  3
all elements of row are:  5
all elements of row are:  6
all elements of row are:  7
all elements of row are:  8
all elements of row are:  9
all elements of row are:  10
